blank_issues_enabled: false
contact_links:
  - name: Mi AI Schedule Official Document
    url: https://open-schedule-prod.ai.xiaomi.com/docs/#/help/
    about: Click to view the official document of Mi AI Schedule.
  - name: 小爱课程表官方文档
    url: https://open-schedule-prod.ai.xiaomi.com/docs/#/help/
    about: 点击查看小爱课程表官方文档。
